# The Basics of Supervised NLP Tasks - School Solution

## 0 - Importing the Data

In [1]:
import pandas as pd

In [2]:
# import io
# import requests
# url = "https://github.com/shaypal5/tau_text_mining_24_5/raw/refs/heads/main/lecture_4/kindle_reviews_tau.csv"

In [3]:
# s = requests.get(url).content
# df = pd.read_csv(io.StringIO(s.decode('utf-8')))

In [4]:
df = pd.read_csv('kindle_reviews_tau.csv')  # use this line instead if you've downloaded the dataset directly

In [5]:
df.head(5)

,asin,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime,total_votes_on_helpfulness,is_helpful_votes,is_helpful_ratio,age,gender,state,yearly_income,is_married,favorite_genre
0,B000FA64PA,5,I think I have this one in both book and audio...,"01 27, 2014",A1ZT7WV0ZUA0OJ,Mike,Audio and book,1390780800,0,0,0.0,23,Male,Utah,43953,False,Horror
1,B000FA64PK,5,This one promises to be another good book. I h...,"01 27, 2014",A1ZT7WV0ZUA0OJ,Mike,my collection,1390780800,1,0,0.0,23,Male,Utah,43953,False,Horror
2,B000FA64QO,5,I was hoping to find this one in book form. Th...,"01 27, 2014",A1ZT7WV0ZUA0OJ,Mike,my e- collection,1390780800,0,0,0.0,23,Male,Utah,43953,False,Horror
3,B000FBFMVG,5,I love the stories with Chewie in them! this e...,"01 27, 2014",A1ZT7WV0ZUA0OJ,Mike,my collection,1390780800,0,0,0.0,23,Male,Utah,43953,False,Horror
4,B000FC26RI,4,As an aspiring yogini this is required reading...,"02 13, 2013",A2Y1X56N8NPH8G,"Heather ""Houndog""",A good resource,1360713600,0,0,0.0,21,Male,Oklahoma,23498,False,Non-Fiction